sudo: true

notifications:
  email:
    - evantahler@gmail.com
language: node_js
node_js:
  - "iojs"
  - "4.0"
  - "5.0"
branches:
  only:
    - master

# We'll manually install versions of ES ourselves
# services:
#   - elasticsearch

# env:
#   - "ES_VERSION=2.3.1"
#   - "ES_VERSION=1.7.4"

before_install:
  # - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch restart
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.3.deb
  - sudo dpkg -i --force-confnew elasticsearch-1.7.3.deb
  - sudo service elasticsearch restart
  - sleep 15
